server:
  port: 9527

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka #单机版

spring:
  application:
    name: gatewey #服务名称
  cloud:
    gateway:
      routes:
        - id: after_route1
#          uri: http://localhost:8001
          uri: lb://PARMENT-SERVICE
          predicates:
            - Path=/payment/getPaymentById/** #满足指定路径才能访问
#            - After=2020-12-28T15:27:20.356+08:00[Asia/Shanghai] #指定某个时间之后才能访问
#            - Before=2020-12-28T15:30:20.356+08:00[Asia/Shanghai] #指定某个时间之前才能访问
#            - Between=2020-12-28T15:36:00.356+08:00[Asia/Shanghai],2020-12-28T15:37:00.356+08:00[Asia/Shanghai] #在指定时间范围内才能访问
#            - Cookie=username,MyComputer #带cookies访问
#            - Header=X-Request-Id, \d+
#            - Host=**.somehost.org,**.anotherhost.org
#            - Method=GET,POST
#            - Path=/red/{segment},/blue/{segment}
#            - Query=green
#            - RemoteAddr=192.168.1.1/24
#            - Weight=group1, 2
          filters:
            - AddRequestHeader=X-Request-red, blue
#        - id: after_route2
#          uri: lb://PARMENT-SERVICE
#          predicates:
#            - Path=/payment/addPayment/**
