server:
  port: 8089

spring:
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    ervice-url:
      defaultZone: http://eureka7001:7001/eureka #单机版
#      defaultZone: http://eureka7001:7001/eureka, http://eureka7002:7002/eureka  #集群版


