server:
  port: 8088

spring:
  application:
    name: feignOrder-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka  #集群版
  instance:
    instance-id: feignOrder-service #设置euerka显示的status名称
    prefer-ip-address: true #设置显示ip